# Mark Shust's Docker Configuration for Magento (https://github.com/markoshust/docker-magento)
# Version 13.0.1

version: "3"

services:
  app:
    build: images/nginx
    ports:
      - 80:8000
    links:
      - db
      - php
    volumes: &appvolumes
      - ./src:/var/www/html:delegated
      - ~/.composer:/var/www/.composer:delegated
      - sockdata:/sock

  php:
    image: markoshust/magento-php:5.6-fpm-3
    links:
      - db
    volumes: *appvolumes

  cron:
    image: markoshust/magento-php:5.6-fpm-3
    user: root
    command: /usr/local/bin/cronstart
    tty: true
    links:
      - db
    volumes: *appvolumes

  db:
    image: percona:5.7
#    image: mysql:5.6
    ports:
      - 3306:3306
    env_file: env/db.env
    volumes:
#      - dbdata_mysql:/var/lib/mysql
     - dbdata_percona:/var/lib/mysql

volumes:
#  dbdata_mysql:
  dbdata_percona:
  sockdata:


# ./bin/xdebug enable
# docker-compose exec --user root php vim /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
### xdebug.remote_host=local.ip.of.my.machine
### xdebug.remote_port=9000
# docker-compose restart php