<?php
/**
 * Created by PhpStorm.
 * User: lucian.toza
 * Date: 16/07/2018
 * Time: 14:18
 */

class First_Sales_Model_Quote_Address extends Mage_Sales_Model_Quote_Address
{

    protected function _construct()
    {
        return parent::_construct(); // TODO: Change the autogenerated stub
    }
}